#!/usr/bin/env python3
"""Unit tests: wikilink parse + golden vault → graph JSON + HTML kg marker."""
from __future__ import annotations

import json
import sys
import tempfile
import unittest
from pathlib import Path
from unittest import mock

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
for _d in (SCRIPTS, SCRIPTS / "memory", SCRIPTS / "dashboard"):
    sys.path.insert(0, str(_d))

from vault_common import extract_wikilinks, parse_frontmatter  # noqa: E402
import graph as knowledge_graph  # noqa: E402
import core as dashboard  # noqa: E402


class TestWikilinks(unittest.TestCase):
    def test_extract(self):
        text = "See [[projects/raven]] and [[concepts/foo|Foo]]."
        links = extract_wikilinks(text)
        self.assertEqual(links, ["projects/raven", "concepts/foo|Foo"])

    def test_frontmatter(self):
        text = "---\ntype: concept\nname: x\n---\n# Hi\n"
        meta, body = parse_frontmatter(text)
        self.assertEqual(meta.get("type"), "concept")
        self.assertIn("# Hi", body)


class TestGraphBuild(unittest.TestCase):
    def test_golden_vault(self):
        with tempfile.TemporaryDirectory() as td:
            vault = Path(td)
            for sub in ("projects", "concepts", "decisions", "sessions", "graph"):
                (vault / sub).mkdir()
            (vault / "projects" / "fin-processor.md").write_text(
                "---\ntype: project\nname: fin-processor\n---\n"
                "# fin\n- [[concepts/workspace]]\n- [[concepts/cards]]\n"
            )
            (vault / "concepts" / "workspace.md").write_text(
                "---\ntype: concept\n---\n# W\n[[projects/fin-processor]]\n"
            )
            (vault / "concepts" / "cards.md").write_text(
                "---\ntype: concept\n---\n# C\n[[projects/fin-processor]]\n"
            )
            (vault / "decisions" / "adr-1.md").write_text(
                "---\ntype: decision\n---\n# ADR\n[[projects/fin-processor]]\n"
            )
            (vault / "sessions" / "2026-08-03-fin-processor.md").write_text(
                "---\ntype: session\nproject: fin-processor\n---\n"
                "[[projects/fin-processor]]\n"
            )
            with mock.patch.object(knowledge_graph, "VAULT", vault), mock.patch.object(
                knowledge_graph, "PROJECTS", vault / "projects"
            ), mock.patch.object(
                knowledge_graph, "CONCEPTS", vault / "concepts"
            ), mock.patch.object(
                knowledge_graph, "DECISIONS", vault / "decisions"
            ), mock.patch.object(
                knowledge_graph, "SESSIONS", vault / "sessions"
            ), mock.patch.object(
                knowledge_graph, "GRAPH_DIR", vault / "graph"
            ):
                g = knowledge_graph.build_graph(
                    project_filter="fin-processor", session_days=None
                )
            self.assertGreaterEqual(len(g["nodes"]), 6)
            self.assertGreaterEqual(len(g["edges"]), 5)


class TestHtmlMarker(unittest.TestCase):
    def test_kg_canvas_or_sparse(self):
        graph = {
            "nodes": [
                {"id": "projects/a", "label": "a", "type": "project", "path": "projects/a.md"},
                {"id": "concepts/b", "label": "b", "type": "concept", "path": "concepts/b.md"},
            ],
            "edges": [{"source": "concepts/b", "target": "projects/a", "rel": "wikilink"}],
        }
        metrics = {
            "by_project": {"a": {"sessions": 1, "tokens": 10, "cost_usd": 0.001}},
            "window_start": "2026-01-01",
            "window_end": "2026-01-31",
            "guard_events": {},
            "violations": {},
            "sessions_count": 1,
            "total_tokens": 10,
            "total_cost_usd": 0.001,
        }
        meta = {"project": "a", "vault_path": str(Path.home() / "RavenVault")}
        section = dashboard.render_knowledge_graph_section(
            graph, metrics=metrics, metadata=meta
        )
        self.assertIn('id="kg-canvas"', section)
        self.assertIn("kgShowNode", section)
        self.assertIn("Summary", section)
        self.assertIn("Generated by Andie - Guru", section)
        sparse = dashboard.render_knowledge_graph_section(
            {"nodes": [], "edges": []}, metrics=metrics, metadata=meta
        )
        self.assertIn("sparse", sparse.lower())


if __name__ == "__main__":
    unittest.main()
